# Generated by Django 5.0.1 on 2024-03-05 06:40

import django.core.validators
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': '편의시설',
                'db_table': 'UserAmenity',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': '시설',
                'db_table': 'UserFacility',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HouseRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': '숙소 이용규칙',
                'verbose_name_plural': '숙소 이용규칙',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='숙소명')),
                ('photo', models.ImageField(upload_to='', verbose_name='사진')),
                ('description', models.TextField(verbose_name='설명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('keyword', models.CharField(choices=[('Kids', 'Kids'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter'), ('Room Only', 'Room Only'), ('Couple', 'Couple'), ('Spa', 'Spa'), ('Suite', 'Suite'), ('HoneyMoon', 'HoneyMoon'), ('Early Check-in', 'Early Check-in'), ('Late Check-out', 'Late Check-out'), ('Breakfast', 'Breakfast'), ('Dinning', 'Dinning')], max_length=100, verbose_name='키워드')),
                ('check_in', models.CharField(max_length=20, verbose_name='체크인')),
                ('check_out', models.CharField(max_length=20, verbose_name='체크아웃')),
                ('check_in_time', models.CharField(max_length=20, verbose_name='체크인 시간')),
                ('check_out_time', models.CharField(max_length=20, verbose_name='체크아웃 시간')),
                ('beds', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='침대')),
                ('bedrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='침실')),
                ('baths', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='욕실')),
                ('room_type', models.CharField(choices=[('Deluxe', 'Deluxe'), ('Studio Suite', 'Studio Suite'), ('Premier Suite', 'Premier Suite'), ('Luxury Suite', 'Luxury Suite'), ('The Suite', 'The Suite'), ('Hill Suite', 'Hill Suite'), ('Prestige Hill Suite', 'Prestige Hill Suite'), ('Superior Room', 'Superior Room'), ('Executive Room', 'Executive Room')], max_length=100, verbose_name='숙소유형')),
                ('amenities', models.ManyToManyField(blank=True, related_name='rooms', to='rooms.amenity', verbose_name='편의시설')),
                ('facilities', models.ManyToManyField(blank=True, related_name='rooms', to='rooms.facility', verbose_name='시설')),
                ('house_rules', models.ManyToManyField(blank=True, related_name='rooms', to='rooms.houserule', verbose_name='숙소 이용규칙')),
            ],
            options={
                'verbose_name': 'rooms',
                'db_table': 'UserRooms',
            },
        ),
    ]
