# Generated by Django 5.0.1 on 2024-03-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(choices=[('Kids', 'Kids'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter'), ('Room Only', 'Room Only'), ('Couple', 'Couple'), ('Spa', 'Spa'), ('Suite', 'Suite'), ('HoneyMoon', 'HoneyMoon'), ('Early Check-in', 'Early Check-in'), ('Late Check-out', 'Late Check-out'), ('Breakfast', 'Breakfast'), ('Dinning', 'Dinning')], max_length=100, verbose_name='키워드')),
            ],
            options={
                'verbose_name': 'keywords',
                'db_table': 'UserKeywords',
            },
        ),
    ]
