# Generated by Django 5.0.1 on 2024-03-05 06:28

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(default='', max_length=20, unique=True, validators=[accounts.validators.validate_id], verbose_name='아이디')),
                ('name', models.CharField(default='', max_length=10, verbose_name='이름')),
                ('phone', models.CharField(max_length=11, null=True, unique=True, validators=[accounts.validators.validate_phone], verbose_name='전화번호')),
                ('email', models.EmailField(max_length=128, unique=True, validators=[accounts.validators.validate_email])),
                ('gender', models.CharField(choices=[('MEN', '남자'), ('WOMEN', '여자')], max_length=10, verbose_name='성별')),
                ('postcode', models.CharField(max_length=10, verbose_name='우편번호')),
                ('detailAddress', models.CharField(max_length=100, verbose_name='자세한 주소')),
                ('address', models.CharField(max_length=128, verbose_name='주소')),
                ('eName1', models.CharField(max_length=20, verbose_name='영어 첫번째 이름')),
                ('eName2', models.CharField(max_length=20, verbose_name='영어 마지막 이름')),
                ('birthday', models.CharField(max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'accounts',
                'db_table': 'UserAccounts',
            },
        ),
    ]
